### ISSUE TITLE
Missing file nevermore_filter.cfg

### ISSUE THREAD

**Issue by neptunus0001** [mjonuschat/voron-modular-config#2]
Hello,

After studying the modular design of the config files, I can say that it was of tremendous help to my personal configuration!

I just discovered a small cosmetic flaw (I think :-))

In the file printer.cfg the lines below are shown.
```
## Air filters
# [include config/hardware/filters/nevermore_filter.cfg]
```
It took me some time to realize that you probably had this config like this in the past and it changed in a way to the bed_fans config in the current setup. 

Two questions:
1: My assumption is correct
2: If my assumption is correct, request to modify for other enthusiasts.

Thank you again so much for sharing, really great work!

**Comment by mjonuschat** [comment]
Hey, this was actually a reference to a early prototype of the Nevermore StealthMax I was running utilizing a custom ESP32 based config being controlled over MQTT. I never ended up publishing this as there have been better controllers for the StealthMax since then. I'll remove the reference from the config.

For the normal Nevermore Duo you'll find the needed config under bed_fans/nevermore_duo.cfg as that's the way I control mine.
